### PR TITLE
Navhover

### PR DESCRIPTION
**Pull request by mr-osiris**
i have changed hover effect by using css.
i have added zoom in and zoom out effect and color change on hover.

### CODE REVIEW

**Comment by pccoe-acm** [comment]
@mr-osiris attach screen shot or video solution

**Comment by mr-osiris** [comment]
Screenshot (9)
Screenshot (8)
Screenshot (7)

**Comment by pccoe-acm** [comment]
@mr-osiris  resolve the conflicts so that i can merge your pr

**Comment by pccoe-acm** [comment]
@mr-osiris resolve the  conflicts as soon as possible

**Pull request closed without merging**
